version: '2'
services:
  clearwaters-server:
    build: server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    restart: always

  clearwaters-client: 
    build: client
    ports:
      - "3001:3001"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - clearwaters-server
    restart: always